# Introduction

In this notebook, we will work through how to read an OpenFOAM case.


In [1]:
import sys, os
davinci_dir = r"C:\daVinci"
sys.path.append(davinci_dir)
from daVinci import *

import numpy as np


Here is the directory of the case that we are using. We can chang this as needed very easily.


In [2]:
case_dir = r"M:\Pinaki\Keeton2025_1D_2x"


# Object Definition 

Now, let's define a rake of 1,000 points from one end to the other. The rake defines a set of points, preferably on a curve, that are sampled. This allows da Vinci to easily sample from a larger set of data.



In [3]:
N_pts = 1000

rake_sample = rake(( np.linspace(0, 0.45, num=N_pts), np.zeros(N_pts), np.zeros(N_pts)), "foam", file_format="foam" )


File list:	[]


# Reader

Next, we can look at using the OpenFOAM reader to get the data.


In [4]:
rake_sample.foamCaseRead( case_dir, verbosity=1, coordinate_system=['x', 'y'] )


The full filename is M:\Pinaki\Keeton2025_1D_2x\foam.foam
Number of cells: 14999
Number of blocks in cell centers: 1
Number of blocks in cell data: 1
Current time step 1e-06 at index 0...
Dropping dimension 1
Current time step 2e-06 at index 1...
Dropping dimension 1
Current time step 3e-06 at index 2...
Dropping dimension 1
Current time step 4e-06 at index 3...
Dropping dimension 1
Current time step 5e-06 at index 4...
Dropping dimension 1
Current time step 6e-06 at index 5...
Dropping dimension 1
Current time step 7e-06 at index 6...
Dropping dimension 1
Current time step 8e-06 at index 7...
Dropping dimension 1
Current time step 9e-06 at index 8...
Dropping dimension 1
Current time step 1e-05 at index 9...
Dropping dimension 1
Current time step 1.1e-05 at index 10...
Dropping dimension 1
Current time step 1.2e-05 at index 11...
Dropping dimension 1
Current time step 1.3e-05 at index 12...
Dropping dimension 1
Current time step 1.4e-05 at index 13...
Dropping dimension 1
Current time

What are the time steps in the case?


In [5]:
print(f"There are {len(rake_sample.time_steps)} time steps")


There are 191 time steps


In [6]:
rake_sample.data_matrix.shape


(25, 14999)

In [7]:
rake_sample.data_dict.keys()


dict_keys(['AR', 'H', 'H2', 'H2O', 'H2O2', 'HNO', 'HO2', 'N', 'N2', 'N2O', 'NH', 'NH2', 'NH3', 'NNH', 'NO', 'NO2', 'O', 'O2', 'OH', 'T', 'mag(U)', 'p', 'rho', 'U:x', 'U:y'])

In [8]:
print("Number of cells:", rake_sample.foam.GetDataInformation().GetNumberOfCells())
print("Available arrays:", [rake_sample.foam.PointData[i].Name for i in range(rake_sample.foam.PointData.GetNumberOfArrays())])


Number of cells: 14999
Available arrays: ['AR', 'H', 'H2', 'H2O', 'H2O2', 'HNO', 'HO2', 'mag(U)', 'N', 'N2', 'N2O', 'NH', 'NH2', 'NH3', 'NNH', 'NO', 'NO2', 'O', 'O2', 'OH', 'p', 'rho', 'T', 'U']


In [9]:
rake_sample.points[:,:2]


array([[0.        , 0.        ],
       [0.00045045, 0.        ],
       [0.0009009 , 0.        ],
       ...,
       [0.4490991 , 0.        ],
       [0.44954955, 0.        ],
       [0.45      , 0.        ]])

In [10]:
rake_sample.cell_coords[:,:2]


array([[1.50010001e-05, 0.00000000e+00],
       [4.50030002e-05, 0.00000000e+00],
       [7.50049985e-05, 0.00000000e+00],
       ...,
       [4.49925005e-01, 0.00000000e+00],
       [4.49955001e-01, 0.00000000e+00],
       [4.49984998e-01, 0.00000000e+00]])

In [11]:
rake_sample.data["U:x"]


array([[-8.98023660e-04,  2.45519914e-07,  1.25728548e-08, ...,
        -9.23871994e-06, -3.18884850e-06, -1.39325857e-06],
       [-1.70362291e-03,  2.88753654e-07,  1.55050657e-07, ...,
         2.04667449e-05, -1.47335231e-06,  8.64081085e-06],
       [-2.43697531e-03,  5.80467258e-07,  2.85963324e-07, ...,
        -7.79717448e-06,  1.64467383e-05,  5.46128431e-05],
       ...,
       [ 3.63511264e+02,  3.63622513e+02,  3.63734772e+02, ...,
         2.10066355e-06,  3.20816616e-06, -4.51903754e-04],
       [ 3.63587127e+02,  3.63701501e+02,  3.63808633e+02, ...,
        -1.32837454e-06,  1.06561370e-05, -4.67686098e-04],
       [ 3.63662868e+02,  3.63772682e+02,  3.63866244e+02, ...,
        -3.70136689e-06,  7.90201796e-06, -4.85707825e-04]])